### ISSUE TITLE
After installing pi4 patchbox module, pi does a shutdown on reboot loop

### ISSUE THREAD

**Issue by yratof** [RowdyVoyeur/m8c-rpi4#8]
After running 

`patchbox module activate m8c-rpi4-module`

the pi is unresponsive, as it reboots, gets to patchbox, ssh is available for 10 seconds before it shutsdown and repeats the process forever. 

the screen it's connected to shows all the commands running before it hits this mark and this the HDMI goes black.

if I run `./m8c.sh` we have a working m8 install. but the module install basically means i need to flash the SD and start again

**Comment by RowdyVoyeur** [comment]
Just tested with a fresh install and didn't have any issues. Could you please provide more information about your system?

**Comment by yratof** [comment]
A raspberry pi 4… 8gb, and your guide that’s pretty much the only two
variables here.

I lose all access to the system if I use the patch box module, I’ve
connected to a TV I can see that immediately after running the patch, the
pi shuts down . Almost like m8 quits, which kicks in the halt

**Comment by RowdyVoyeur** [comment]
I wonder if the 8gb are the culprit. I've read some complaints about using RPi4 8gb with MODEP, for instance. Have you tried to install/run other modules?

After reading your original message again, I believe the issue could be related to permissions. All the module does is run m8c.sh. if the system doesn't have permissions to execute some actions within the script, it will jump to the end of it and shutdown - and it could reboot because you're installing the module.

One way to test this would be to comment the final lines of the m8c.sh to prevent the script from shutting down.

**Comment by yratof** [comment]
No, I have no idea what else i would use. You have any demo projects I
could test?

**Comment by RowdyVoyeur** [comment]
If you want to test modules, your safest bet would be Patchbox modules. You could install any of the following: https://blokas.io/patchbox-os/docs/modules/

If you're feeling lucky and don't mind redoing everything from scratch if something goes wrong, you could comment the final lines of m8c.sh to disable shutdown on quit and install the module.

**Comment by yratof** [comment]
I’ll do that first, if it doesn’t shutdown, it should log the errors

**Comment by RowdyVoyeur** [comment]
Good luck. Please keep me posted!

**Comment by RowdyVoyeur** [comment]
Did you have any luck?

**Comment by RowdyVoyeur** [comment]
Since I haven't heard back from you and nobody else complained about the same issue, I will close this.

**Comment by RowdyVoyeur** [comment]
Since I haven't heard back from you and nobody else complained about the same issue, I will close this.

**Comment by yratof** [comment]
Damn I was replying the other day and seems like I got as far as putting an emoji on a comment. 

Removing those line fixed it, in the sense that it loads m8 and everything works fine. There's technically no reason to shutdown, unless we're using pi5 which have a shutdown switch now.

But to conclude, without the kill, it loads and works. So for some reason, during the start up, it's being told to turn off

**Comment by RowdyVoyeur** [comment]
No worries. Thanks for replying.

Well, my suspicions were wrong However, it shouldn't be related to the module either.

I wonder why it shuts down with those final lines - they should only shutdown after quitting m8c. 

Please let me know if you need help with anything else. Otherwise, I'll keep this closed.
